# Fetch API 
- No API-key requiered

In [21]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv

load_dotenv()
CONTACT = os.getenv("MB_CONTACT")

url = "https://musicbrainz.org/ws/2/recording"
headers = {"User-Agent": f"MusikQuizApp/0.1 ({CONTACT})"}
params = {
    "query": "tag:rock AND date:[1980 TO 1989]",
    "limit": 25,
    "fmt": "json",
}

r = requests.get(url, params=params, headers=headers, timeout=30)
r.raise_for_status()

df = pd.json_normalize(r.json()["recordings"])
df.columns

Index(['id', 'score', 'artist-credit-id', 'title', 'length', 'disambiguation',
       'video', 'artist-credit', 'first-release-date', 'releases', 'isrcs',
       'tags'],
      dtype='str')

### Fetch data using function

In [22]:
import os
import time
import requests
import pandas as pd
from dotenv import load_dotenv

load_dotenv()  # reads in .env

BASE_URL = "https://musicbrainz.org/ws/2"
CONTACT = os.getenv("MB_CONTACT")
if not CONTACT:
    raise RuntimeError("MB_CONTACT missing in .env")

HEADERS = {"User-Agent": f"MusikQuizApp/0.1 ({CONTACT})"}

def mb_get(endpoint, params):
    params = {**params, "fmt": "json"}
    r = requests.get(f"{BASE_URL}/{endpoint}", params=params, headers=HEADERS, timeout=30)
    r.raise_for_status()
    time.sleep(1)  # rate limit
    return r.json()

# Ex: recordnings from the 80's by a certain artist
data = mb_get("recording", {
    "query": 'artist:"a-ha" AND date:[1980 TO 1989]',
    "limit": 100,
    "offset": 0,
})

print(data["count"])
print(data["recordings"][0])

100

### Some EDA artist "a-ha" between dates 1980 - 1989

In [23]:
# Check columns 
df = pd.json_normalize(data["recordings"])
df.columns

Index(['id', 'score', 'artist-credit-id', 'title', 'length', 'video',
       'artist-credit', 'first-release-date', 'releases', 'isrcs', 'tags',
       'disambiguation'],
      dtype='str')

In [24]:
# first rows
df.head()

,id,score,artist-credit-id,title,length,video,artist-credit,first-release-date,releases,isrcs,tags,disambiguation
0,42f98955-ed53-48d3-8c31-578f1c63d935,100,07885c4d-864e-30be-ba2b-541c03409c3b,Manhattan Skyline,290000.0,None,"[{'name': 'a‐ha', 'artist': {'id': '7364dea6-c...",1986-11-27,[{'id': '2d147ea1-d1b6-4a2c-b117-94f7cafcb049'...,[USWB10107602],"[{'count': 1, 'name': 'rock'}, {'count': 2, 'n...",NaN
1,b21ec767-1814-4107-8673-7805906d6378,100,07885c4d-864e-30be-ba2b-541c03409c3b,There's Never a Forever Thing,168000.0,None,"[{'name': 'a‐ha', 'artist': {'id': '7364dea6-c...",1988,[{'id': '93d73efa-866e-461a-bd6e-152163bb2a70'...,NaN,NaN,NaN
2,944acd96-072f-4714-bf9b-d8a1e9189d35,100,07885c4d-864e-30be-ba2b-541c03409c3b,We’re Looking for the Whales (live version),412000.0,None,"[{'name': 'a‐ha', 'artist': {'id': '7364dea6-c...",1987-05-25,[{'id': '153bc4f7-f77c-493b-a580-12d860d7fca4'...,NaN,NaN,NaN
3,1002235f-43ec-4c1f-abdb-a7ecc9f90f44,100,07885c4d-864e-30be-ba2b-541c03409c3b,Take On Me,227000.0,None,"[{'name': 'a‐ha', 'artist': {'id': '7364dea6-c...",1989,[{'id': 'df0e75ae-4ac5-4d35-9bab-f8b4deda6868'...,NaN,NaN,live
4,2f97a4d3-8ea0-4dff-8d70-0921fe8bc609,100,07885c4d-864e-30be-ba2b-541c03409c3b,The Sun Always Shines On T.V. (instrumental),400000.0,None,"[{'name': 'a‐ha', 'artist': {'id': '7364dea6-c...",1985,[{'id': '739f5e52-36d7-489f-8055-f4ca54b4733b'...,NaN,NaN,NaN

In [25]:
# types and number of missing values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  100 non-null    str
 1   score               100 non-null    int64
 2   artist-credit-id    100 non-null    str
 3   title               100 non-null    str
 4   length              95 non-null     float64
 5   video               0 non-null      object
 6   artist-credit       100 non-null    object
 7   first-release-date  100 non-null    str
 8   releases            100 non-null    object
 9   isrcs               2 non-null      object
 10  tags                7 non-null      object
 11  disambiguation      11 non-null     str
dtypes: float64(1), int64(1), object(5), str(5)
memory usage: 19.6+ KB

In [26]:
# number of rows and columns
df.shape

(100, 12)

### Check with another artist and years

In [27]:
data = mb_get("recording", {
    "query": 'artist:"Britney Spears" AND date:[1995 TO 2005]',
    "limit": 100,
    "offset": 0,
})

print(data["count"])
print(data["recordings"][0])

488
{'id': 'b89f48bb-5dce-4ce3-aec9-364477f526fa', 'score': 100, 'artist-credit-id': '038401cc-de8b-3013-9efe-4ee3e07782f6', 'title': 'Boys', 'length': 242000, 'disambiguation': 'part of “The Very Best of Pure R&B: The Summer Collection” DJ‐mix', 'video': None, 'artist-credit': [{'name': 'Britney Spears', 'artist': {'id': '45a663b5-b1cb-4a91-bff6-2bef7bbfdd76', 'name': 'Britney Spears', 'sort-name': 'Spears, Britney', 'aliases': [{'sort-name': '브리트니 스피어스', 'type-id': '1937e404-b981-3cb7-8151-4c86ebfc8d8e', 'name': '브리트니 스피어스', 'locale': None, 'type': 'Search hint', 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'ブリトニー・スピアーズ', 'type-id': '894afba6-2816-3c24-8072-eadb66bd04bc', 'name': 'ブリトニー・スピアーズ', 'locale': 'ja', 'type': 'Artist name', 'primary': True, 'begin-date': None, 'end-date': None}, {'sort-name': 'Bretney Spears', 'name': 'Bretney Spears', 'locale': None, 'type': None, 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'B. Spears', 'name': 'B. Spears', 'locale': None, 'type': None, 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'Brittany Spears', 'name': 'Brittany Spears', 'locale': None, 'type': None, 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'Briteny Spears', 'name': 'Briteny Spears', 'locale': None, 'type': None, 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'Brittney Spears', 'name': 'Brittney Spears', 'locale': None, 'type': None, 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'Spears, Britney Jean', 'type-id': 'd4dcd0c0-b341-3612-a332-c0ce797b25cf', 'name': 'Britney Jean Spears', 'locale': None, 'type': 'Legal name', 'primary': None, 'begin-date': None, 'end-date': None}]}}], 'first-release-date': '2003-03-31', 'releases': [{'id': 'dfeca7a0-f9c8-48e3-b609-24debb4769be', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'artist-credit-id': '949a7fd5-fe73-3e8f-922e-01ff4ca958f7', 'count': 2, 'title': 'The Very Best of Pure R&B: The Summer Collection 2003', 'status': 'Official', 'artist-credit': [{'name': 'Various Artists', 'artist': {'id': '89ad4ac3-39f7-470e-963a-56509c546377', 'name': 'Various Artists', 'sort-name': 'Various Artists', 'disambiguation': 'add compilations to this artist'}}], 'release-group': {'id': 'ccbfb1c6-35c4-397b-9e33-dbb4a5989a28', 'type-id': 'dd2a21e1-0c00-3729-a7a0-de60b84eb5d1', 'primary-type-id': 'f529b476-6e62-324f-b0aa-1f3e33d313fc', 'title': 'The Very Best of Pure R&B: The Summer Collection 2003', 'primary-type': 'Album', 'secondary-types': ['Compilation', 'DJ-mix'], 'secondary-type-ids': ['dd2a21e1-0c00-3729-a7a0-de60b84eb5d1', '0d47f47a-3fe5-3d69-ac9d-d566c23968bf']}, 'date': '2003-03-31', 'country': 'GB', 'release-events': [{'date': '2003-03-31', 'area': {'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed', 'name': 'United Kingdom', 'sort-name': 'United Kingdom', 'iso-3166-1-codes': ['GB']}}], 'track-count': 40, 'media': [{'id': 'af0fa4b4-6946-3476-bee3-8b5bc8cf31a5', 'position': 2, 'format': 'CD', 'track': [{'id': '2c9e94bc-d378-3155-81a9-6f9a0995b613', 'number': '8', 'title': 'Boys', 'length': 242000}], 'track-count': 20, 'track-offset': 7}]}]}

In [28]:
df = pd.json_normalize(data["recordings"])
df.columns

Index(['id', 'score', 'artist-credit-id', 'title', 'length', 'disambiguation',
       'video', 'artist-credit', 'first-release-date', 'releases', 'isrcs',
       'tags'],
      dtype='str')

In [29]:
df.head()

,id,score,artist-credit-id,title,length,disambiguation,video,artist-credit,first-release-date,releases,isrcs,tags
0,b89f48bb-5dce-4ce3-aec9-364477f526fa,100,038401cc-de8b-3013-9efe-4ee3e07782f6,Boys,242000.0,part of “The Very Best of Pure R&B: The Summer...,None,"[{'name': 'Britney Spears', 'artist': {'id': '...",2003-03-31,[{'id': 'dfeca7a0-f9c8-48e3-b609-24debb4769be'...,NaN,NaN
1,5286dc3a-c699-4784-8bde-12701932f0fd,100,038401cc-de8b-3013-9efe-4ee3e07782f6,(You Drive Me) Crazy (The Stop Remix!) (instru...,199400.0,NaN,None,"[{'name': 'Britney Spears', 'artist': {'id': '...",1999-09-29,[{'id': '9eb6afce-a06c-468c-8bca-1408a8881f0f'...,[USJI19910720],"[{'count': 1, 'name': 'electronic'}, {'count':..."
2,fb975c61-c934-4880-835e-d23437401b25,100,038401cc-de8b-3013-9efe-4ee3e07782f6,(You Drive Me) Crazy (Jazzy Jim’s hip-hop mix),220000.0,NaN,None,"[{'name': 'Britney Spears', 'artist': {'id': '...",1999-12-06,[{'id': 'acaee915-0ecd-4e3a-a112-be1d2e6d9641'...,NaN,"[{'count': 3, 'name': 'pop'}, {'count': 1, 'na..."
3,d9a51139-373d-48ab-9539-2af59860a2b3,100,038401cc-de8b-3013-9efe-4ee3e07782f6,Right Now (Taste the Victory),314760.0,NaN,None,"[{'name': 'Britney Spears', 'artist': {'id': '...",2002-04,[{'id': '54593f6e-5251-439c-a45b-102b940773da'...,NaN,NaN
4,2c4e741b-b0d0-452a-994e-226925516632,100,038401cc-de8b-3013-9efe-4ee3e07782f6,Toxic,186000.0,NaN,None,"[{'name': 'Britney Spears', 'artist': {'id': '...",2004,[{'id': '3ef19145-4c5a-4ede-8d0f-1c9a4c3c225b'...,NaN,NaN

### Test with 'genre' and 'relese'

In [32]:
data = mb_get("recording", {
    "query": 'genre:"pop" AND relese:[2005]',
    "limit": 100,
    "offset": 0,
})
print(data)

{'created': '2026-10-12T09:16:49.401Z', 'count': 7715477, 'offset': 0, 'recordings': [{'id': 'd2fd57de-995c-41d4-be13-179d3ca7b37c', 'score': 100, 'artist-credit-id': 'a4ea3a21-77ec-3f61-aed9-56e440b9f043', 'title': 'Pop Sub Genre', 'length': 373136, 'video': None, 'artist-credit': [{'name': 'Daffodill', 'artist': {'id': 'a1d48753-eb5e-40cf-a881-27163c0dd264', 'name': 'Daffodill', 'sort-name': 'Daffodill', 'disambiguation': 'Stephen Davies'}}], 'first-release-date': '2024-04-25', 'releases': [{'id': '4736c140-77ae-47a8-9d70-10db8d801eea', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'count': 1, 'title': 'CHASTITY, 159', 'status': 'Official', 'release-group': {'id': '4e985c85-c302-470f-9e4f-1dd8d1deec7e', 'type-id': 'f529b476-6e62-324f-b0aa-1f3e33d313fc', 'primary-type-id': 'f529b476-6e62-324f-b0aa-1f3e33d313fc', 'title': 'CHASTITY, 159', 'primary-type': 'Album'}, 'date': '2024-04-25', 'country': 'XW', 'release-events': [{'date': '2024-04-25', 'area': {'id': '525d4e18-3d00-31b9-a58b-a146a916de8f', 'name': '[Worldwide]', 'sort-name': '[Worldwide]', 'iso-3166-1-codes': ['XW']}}], 'track-count': 8, 'media': [{'id': 'ccc14aea-6ae3-41a2-8fec-0b9e06220f8e', 'position': 1, 'format': 'Digital Media', 'track': [{'id': 'e6305a9a-bc0e-4d9a-b531-fecea3e9b0d7', 'number': '4', 'title': 'Pop Sub Genre', 'length': 373136}], 'track-count': 8, 'track-offset': 3}]}]}, {'id': 'fa427675-f624-4fb4-94ff-2e0487eeeb80', 'score': 91, 'artist-credit-id': '0519cbf0-f286-3cf7-96da-8f0f13478567', 'title': 'Silver', 'video': None, 'artist-credit': [{'name': 'Relese', 'artist': {'id': '34cf8d4a-4943-4541-93af-13b7f3cfbab9', 'name': 'Relese', 'sort-name': 'Relese'}}], 'first-release-date': '2001-03-11', 'releases': [{'id': '9230145a-2f26-4f70-bc0a-18a97c0b403d', 'artist-credit-id': '949a7fd5-fe73-3e8f-922e-01ff4ca958f7', 'count': 1, 'title': 'Standing on the Shoulders of Giants: A 311 Tribute', 'artist-credit': [{'name': 'Various Artists', 'artist': {'id': '89ad4ac3-39f7-470e-963a-56509c546377', 'name': 'Various Artists', 'sort-name': 'Various Artists', 'disambiguation': 'add compilations to this artist'}}], 'release-group': {'id': '37f2a476-22d8-3cc2-902a-ed8534dc147d', 'type-id': 'dd2a21e1-0c00-3729-a7a0-de60b84eb5d1', 'primary-type-id': 'f529b476-6e62-324f-b0aa-1f3e33d313fc', 'title': 'Standing on the Shoulders of Giants: A 311 Tribute', 'primary-type': 'Album', 'secondary-types': ['Compilation'], 'secondary-type-ids': ['dd2a21e1-0c00-3729-a7a0-de60b84eb5d1']}, 'date': '2001-03-11', 'country': 'XW', 'release-events': [{'date': '2001-03-11', 'area': {'id': '525d4e18-3d00-31b9-a58b-a146a916de8f', 'name': '[Worldwide]', 'sort-name': '[Worldwide]', 'iso-3166-1-codes': ['XW']}}], 'track-count': 24, 'media': [{'id': 'f37dfb86-5027-3e52-9fc5-5282d552b5f8', 'position': 1, 'format': 'CD', 'track': [{'id': 'f6f63f72-b3c2-3d12-a642-0bd200f93463', 'number': '15', 'title': 'Silver'}], 'track-count': 24, 'track-offset': 14}]}]}, {'id': 'd5c6799a-8fa2-41d8-8e8e-e8e74a193ff4', 'score': 82, 'artist-credit-id': '701b6f2c-e323-4440-98a0-ea4c25e95697', 'title': 'Popular Music Genre', 'length': 60330, 'video': None, 'artist-credit': [{'name': 'Arcangel Legrand - Brotherswagg', 'artist': {'id': '9e48b931-4fdb-4233-88dd-f7c7d15c7eab', 'name': 'Arcangel Legrand - Brotherswagg', 'sort-name': 'Arcangel Legrand - Brotherswagg', 'disambiguation': 'Haitian rapper/producer', 'aliases': [{'sort-name': 'Akanj Legran', 'type-id': '894afba6-2816-3c24-8072-eadb66bd04bc', 'name': 'Akanj Legran', 'locale': 'en', 'type': 'Artist name', 'primary': None, 'begin-date': '2011', 'end-date': '2017'}, {'sort-name': 'DIEUDELIN ROBERT', 'type-id': 'd4dcd0c0-b341-3612-a332-c0ce797b25cf', 'name': 'ROBERT DIEUDELIN', 'locale': 'en', 'type': 'Legal name', 'primary': True, 'begin-date': '1999-09-07', 'end-date': None}, {'sort-name': 'Atis Tireray', 'type-id': '894afba6-2816-3c24-8072-eadb66bd04bc', 'name': 'Atis Tireray', 'locale': 'en', 'type': 'Artist name', 'primary': None, 'begin-date': '2008', 'end-date': '2011'}]}}], 'first-release-date': '2027-12-13', 'releases': [{'id': 'ce1e61ac-c76e-429f-9d41-d15f055876e2', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'artist-credit-id': '701b6f2c-e323-4440-98a0-ea4c25e95697', 'count': 1, 'title': 'The Instrumental Experience', 'status': 'Official', 'disambiguation': 'Instrumental album, 2027', 'artist-credit': [{'name': 'Arcangel Legrand - Brotherswagg', 'artist': {'id': '9e48b931-4fdb-4233-88dd-f7c7d15c7eab', 'name': 'Arcangel Legrand - Brotherswagg', 'sort-name': 'Arcangel Legrand - Brotherswagg', 'disambiguation': 'Haitian rapper/producer'}}], 'release-group': {'id': 'a8cf5c31-ca74-49ac-899e-f0b0c6726285', 'type-id': 'f529b476-6e62-324f-b0aa-1f3e33d313fc', 'primary-type-id': 'f529b476-6e62-324f-b0aa-1f3e33d313fc', 'title': 'The Instrumental Experience', 'primary-type': 'Album'}, 'date': '2027-12-13', 'country': 'XW', 'release-events': [{'date': '2027-12-13', 'area': {'id': '525d4e18-3d00-31b9-a58b-a146a916de8f', 'name': '[Worldwide]', 'sort-name': '[Worldwide]', 'iso-3166-1-codes': ['XW']}}], 'track-count': 13, 'media': [{'id': 'f333e14f-ec76-4c5a-9be8-8472b3f6f0ea', 'position': 1, 'format': 'Digital Media', 'track': [{'id': 'a6e9d5ef-5c84-44d2-8c76-9ee7114a7113', 'number': '10', 'title': 'Popular Music Genre', 'length': 60330}], 'track-count': 13, 'track-offset': 9}]}]}, {'id': '200e5f3b-3681-4351-abeb-75c642149543', 'score': 80, 'artist-credit-id': '0f62e159-a9ad-3cac-96dd-59326497b18c', 'title': 'Multiple Genre Genre', 'video': None, 'artist-credit': [{'name': 'Champion the Underdog', 'artist': {'id': '6eeb8d04-85c0-4ee9-aa7f-583b83de8396', 'name': 'Champion the Underdog', 'sort-name': 'Champion the Underdog'}}], 'first-release-date': '2014-06-06', 'releases': [{'id': 'a5de97db-758d-4924-9093-a346288d393d', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'count': 1, 'title': 'Micro Terror Demo EP', 'status': 'Official', 'release-group': {'id': '0b01a60f-d001-44bb-97e9-9aab6fc443e6', 'type-id': '6d0c5bf6-7a33-3420-a519-44fc63eedebf', 'primary-type-id': '6d0c5bf6-7a33-3420-a519-44fc63eedebf', 'title': 'Micro Terror Demo EP', 'primary-type': 'EP'}, 'date': '2014-06-06', 'country': 'XW', 'release-events': [{'date': '2014-06-06', 'area': {'id': '525d4e18-3d00-31b9-a58b-a146a916de8f', 'name': '[Worldwide]', 'sort-name': '[Worldwide]', 'iso-3166-1-codes': ['XW']}}], 'track-count': 5, 'media': [{'id': '28f3229a-5794-37d8-9a68-eb0622ec62c8', 'position': 1, 'format': 'Digital Media', 'track': [{'id': '7f958971-24bf-4230-addc-1e7b44694d40', 'number': '4', 'title': 'Multiple Genre Genre'}], 'track-count': 5, 'track-offset': 3}]}], 'isrcs': ['TCABW1482324']}, {'id': '31ae84bf-a0ec-413c-9c8f-824e73b9415f', 'score': 79, 'artist-credit-id': '2673e1ad-09df-30c7-b730-2e87f720d10e', 'title': 'Genres - Pop', 'length': 107933, 'video': None, 'artist-credit': [{'name': 'Brett Manning', 'artist': {'id': 'c6322470-a653-4a08-9d5d-0b2ab0ed73d7', 'name': 'Brett Manning', 'sort-name': 'Manning, Brett'}}], 'releases': [{'id': '3a21ff1f-0173-4560-83ed-23297e34ec35', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'count': 12, 'title': 'Singing Success', 'status': 'Official', 'release-group': {'id': 'c1b25878-74eb-47a1-8cd9-553a0365058f', 'type-id': '4fc3be2b-de1e-396b-a933-beb8f1607a22', 'primary-type-id': '4fc3be2b-de1e-396b-a933-beb8f1607a22', 'title': 'Singing Success', 'primary-type': 'Other', 'secondary-types': ['Spokenword'], 'secondary-type-ids': ['66b8a13e-43ff-3ac0-ac6c-73659d3817c6']}, 'track-count': 302, 'media': [{'id': 'f962851b-b8d1-3a46-b471-baec3a7940e0', 'position': 2, 'format': 'CD', 'track': [{'id': '4d69191b-55c8-308c-90a5-6e2dab9836ef', 'number': '11', 'title': 'Genres - Pop', 'length': 107933}], 'track-count': 17, 'track-offset': 10}]}]}, {'id': 'b244fb0c-df32-4415-8579-0df3dcfde217', 'score': 78, 'artist-credit-id': 'ad5cd1d1-d92b-3d38-9da3-6edc291e7ab2', 'title': 'Form and Genre', 'video': None, 'artist-credit': [{'joinphrase': ' & ', 'name': 'Professor William R. Cook', 'artist': {'id': 'a76c767c-962d-44e5-8725-7aa4586b1508', 'name': 'William R. Cook', 'sort-name': 'Cook, William R.'}}, {'name': 'Professor Ronald B. Herzman', 'artist': {'id': '05622fa2-188a-47b7-be99-d853382017c9', 'name': 'Ronald B. Herzman', 'sort-name': 'Herzman, Ronald B.'}}], 'releases': [{'id': 'd50b477e-d320-4522-8442-58758d7d71e6', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'count': 1, 'title': 'St. Augustine’s Confessions', 'status': 'Official', 'release-group': {'id': 'f9604bae-084b-4825-b153-b93f03e4d00d', 'type-id': '4fc3be2b-de1e-396b-a933-beb8f1607a22', 'primary-type-id': '4fc3be2b-de1e-396b-a933-beb8f1607a22', 'title': 'St. Augustine’s Confessions', 'primary-type': 'Other', 'secondary-types': ['Spokenword'], 'secondary-type-ids': ['66b8a13e-43ff-3ac0-ac6c-73659d3817c6']}, 'track-count': 24, 'media': [{'id': '9dbf0d0e-57df-33d8-a244-0c28942c2a5e', 'position': 1, 'format': 'Digital Media', 'track': [{'id': 'ef539987-0493-3bad-861b-e6efa1193f1c', 'number': '4', 'title': 'Form and Genre'}], 'track-count': 24, 'track-offset': 3}]}]}, {'id': '77aa32b5-f863-4e77-8b78-1dfbafe0687e', 'score': 78, 'artist-credit-id': '75f71412-00db-3f4b-b247-6762d9debe45', 'title': 'Genre', 'length': 500571, 'video': None, 'artist-credit': [{'name': 'F-6', 'artist': {'id': 'd464f311-bf85-47b6-b5cc-8b29c1a2e91f', 'name': 'F-6', 'sort-name': 'F-6', 'disambiguation': 'Trance producer from Croatia', 'aliases': [{'sort-name': 'Galeković, Filip', 'type-id': 'd4dcd0c0-b341-3612-a332-c0ce797b25cf', 'name': 'Filip Galeković', 'locale': 'hr_HR', 'type': 'Legal name', 'primary': None, 'begin-date': None, 'end-date': None}]}}], 'first-release-date': '2013-03-04', 'releases': [{'id': '358e24fb-be20-4c53-855c-144c878549c5', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'artist-credit-id': '75f71412-00db-3f4b-b247-6762d9debe45', 'count': 1, 'title': 'Genre / Black', 'status': 'Official', 'artist-credit': [{'name': 'F-6', 'artist': {'id': 'd464f311-bf85-47b6-b5cc-8b29c1a2e91f', 'name': 'F-6', 'sort-name': 'F-6', 'disambiguation': 'Trance producer from Croatia'}}], 'release-group': {'id': 'e1ef48bd-3407-4cae-b64f-f07b619bbcee', 'type-id': 'd6038452-8ee0-3f68-affc-2de9a1ede0b9', 'primary-type-id': 'd6038452-8ee0-3f68-affc-2de9a1ede0b9', 'title': 'Genre / Black', 'primary-type': 'Single'}, 'date': '2013-03-04', 'country': 'IE', 'release-events': [{'date': '2013-03-04', 'area': {'id': '390b05d4-11ec-3bce-a343-703a366b34a5', 'name': 'Ireland', 'sort-name': 'Ireland', 'iso-3166-1-codes': ['IE']}}], 'track-count': 2, 'media': [{'id': '9265a83d-3904-31ae-a77a-f0bae24c5b9f', 'position': 1, 'format': 'Digital Media', 'track': [{'id': '3e703ecf-3820-44b4-b2be-8d49688b572b', 'number': '1', 'title': 'Genre', 'length': 500571}], 'track-count': 2, 'track-offset': 0}]}], 'isrcs': ['GBKQU1350133']}, {'id': '53b7f83f-f913-42a8-b75d-a787839ca31c', 'score': 78, 'artist-credit-id': '351a2ab1-cc2c-44a7-bd9c-6569d6ab2ed4', 'title': 'Genre', 'length': 1441000, 'video': None, 'artist-credit': [{'name': 'DJ Robby Bobby', 'artist': {'id': '455cef22-d650-494f-b0fa-2be34f97b330', 'name': 'DJ Robby Bobby', 'sort-name': 'Robby Bobby, DJ', 'disambiguation': 'DJ Robby Bobby'}}], 'first-release-date': '2021-01-10', 'releases': [{'id': '8434c902-2495-4581-b3cc-19638453655d', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'count': 1, 'title': 'Brain Ow (Colorful Anagrams)', 'status': 'Official', 'release-group': {'id': '4ff8d768-550f-4264-b5c4-08fbdca12945', 'type-id': 'f529b476-6e62-324f-b0aa-1f3e33d313fc', 'primary-type-id': 'f529b476-6e62-324f-b0aa-1f3e33d313fc', 'title': 'Brain Ow (Colorful Anagrams)', 'primary-type': 'Album'}, 'date': '2021-01-10', 'country': 'XW', 'release-events': [{'date': '2021-01-10', 'area': {'id': '525d4e18-3d00-31b9-a58b-a146a916de8f', 'name': '[Worldwide]', 'sort-name': '[Worldwide]', 'iso-3166-1-codes': ['XW']}}], 'track-count': 7, 'media': [{'id': '0dd3d388-4a18-3716-811b-946efa70f26b', 'position': 1, 'format': 'Digital Media', 'track': [{'id': 'e5210a06-2547-4577-a772-89d5d1f23c4d', 'number': '4', 'title': 'Genre', 'length': 1441000}], 'track-count': 7, 'track-offset': 3}]}]}, {'id': '1b01a5d7-fb6d-4291-bdf3-805a027d75de', 'score': 78, 'artist-credit-id': '7671f582-077c-370c-b8b7-d843da277d72', 'title': 'Genre', 'length': 441680, 'video': None, 'artist-credit': [{'name': 'Hi Hawaii', 'artist': {'id': 'e08fcb1d-a73e-46cb-9140-6348c37b051f', 'name': 'Hi Hawaii', 'sort-name': 'Hi Hawaii', 'disambiguation': "Belgian duo, formerly 'Geroezemoes'"}}], 'releases': [{'id': '6dc2ac94-000a-48d9-96f9-8305f7d28118', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'count': 1, 'title': 'Hi Hawaii', 'status': 'Official', 'release-group': {'id': '0619cb08-1207-49c4-8a65-c6aa246d4e8d', 'type-id': '6d0c5bf6-7a33-3420-a519-44fc63eedebf', 'primary-type-id': '6d0c5bf6-7a33-3420-a519-44fc63eedebf', 'title': 'Hi Hawaii', 'primary-type': 'EP'}, 'track-count': 7, 'media': [{'id': '4ad8222b-c3bd-37ae-bd46-dbba7ef89b5e', 'position': 1, 'format': 'CD', 'track': [{'id': '724b2eac-ca5d-4421-a1ae-3a0ea6c553df', 'number': '2', 'title': 'Genre', 'length': 441680}], 'track-count': 7, 'track-offset': 1}]}]}, {'id': 'ff0e6ddc-a161-4a8e-9271-6d8c04b16a82', 'score': 78, 'artist-credit-id': '8e863674-3722-3905-832d-81b8eb37730c', 'title': 'Genre', 'length': 284893, 'video': None, 'artist-credit': [{'name': 'Jan Erik Vold', 'artist': {'id': '497b0242-945f-4c36-9aa8-d60315286daa', 'name': 'Jan Erik Vold', 'sort-name': 'Vold, Jan Erik'}}], 'first-release-date': '1994', 'releases': [{'id': '66beaf46-9033-43f8-aa7b-a8324212d75e', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'count': 1, 'title': 'Obstfelder live på Rebekka West', 'status': 'Official', 'release-group': {'id': '3bcb3206-f554-3af8-862e-e4abbaf30977', 'type-id': '6fd474e2-6b58-3102-9d17-d6f7eb7da0a0', 'primary-type-id': 'f529b476-6e62-324f-b0aa-1f3e33d313fc', 'title': 'Obstfelder live på Rebekka West', 'primary-type': 'Album', 'secondary-types': ['Live'], 'secondary-type-ids': ['6fd474e2-6b58-3102-9d17-d6f7eb7da0a0']}, 'date': '1994', 'country': 'NO', 'release-events': [{'date': '1994', 'area': {'id': '6743d351-6f37-3049-9724-5041161fff4d', 'name': 'Norway', 'sort-name': 'Norway', 'iso-3166-1-codes': ['NO']}}], 'track-count': 19, 'media': [{'id': '7efedbbf-1a0d-3591-aea6-6d675f57dd38', 'position': 1, 'format': 'CD', 'track': [{'id': '8be92ca1-0d15-3870-995a-6cb8a6e25323', 'number': '4', 'title': 'Genre', 'length': 284893}], 'track-count': 19, 'track-offset': 3}]}]}, {'id': 'd34811d6-a6df-45c7-a772-ed5626bb681a', 'score': 78, 'artist-credit-id': 'ccb88ad9-9489-4fbe-97ff-24bdb4fe9a37', 'title': 'genre', 'length': 72000, 'video': None, 'artist-credit': [{'name': 'WadeLen', 'artist': {'id': '6c790bba-0ca6-44ca-8334-d1cd9c860eb1', 'name': 'WadeLen', 'sort-name': 'WadeLen', 'aliases': [{'sort-name': 'oldManGuitar', 'type-id': '894afba6-2816-3c24-8072-eadb66bd04bc', 'name': 'oldManGuitar', 'locale': None, 'type': 'Artist name', 'primary': None, 'begin-date': None, 'end-date': None}, {'sort-name': 'Wade Van Eaton', 'type-id': 'd4dcd0c0-b341-3612-a332-c0ce797b25cf', 'name': 'Wade Van Eaton', 'locale': None, 'type': 'Legal name', 'primary': None, 'begin-date': None, 'end-date': None}]}}], 'first-release-date': '2026-06-08', 'releases': [{'id': '142ebc69-4f6d-4b80-a005-60b21d059faf', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'artist-credit-id': 'ccb88ad9-9489-4fbe-97ff-24bdb4fe9a37', 'count': 1, 'title': 'catalog', 'status': 'Official', 'artist-credit': [{'name': 'WadeLen', 'artist': {'id': '6c790bba-0ca6-44ca-8334-d1cd9c860eb1', 'name': 'WadeLen', 'sort-name': 'WadeLen'}}], 'release-group': {'id': '4b0dfc27-9bfd-481c-86a7-49113e4980bb', 'type-id': 'dd2a21e1-0c00-3729-a7a0-de60b84eb5d1', 'primary-type-id': 'f529b476-6e62-324f-b0aa-1f3e33d313fc', 'title': 'catalog', 'primary-type': 'Album', 'secondary-types': ['Compilation'], 'secondary-type-ids': ['dd2a21e1-0c00-3729-a7a0-de60b84eb5d1']}, 'date': '2026-07-12', 'country': 'US', 'release-events': [{'date': '2026-07-12', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'name': 'United States', 'sort-name': 'United States', 'iso-3166-1-codes': ['US']}}], 'track-count': 504, 'media': [{'id': '49625df9-6873-4efe-a4a7-9ac4649d4226', 'position': 1, 'format': 'Data DVD-R', 'track': [{'id': 'c3e5a06b-5e40-402b-86a9-315018203f1d', 'number': '116', 'title': 'genre', 'length': 72000}], 'track-count': 504, 'track-offset': 115}]}, {'id': 'df7d4868-8295-48ad-84df-7afb3135d97a', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'artist-credit-id': 'ccb88ad9-9489-4fbe-97ff-24bdb4fe9a37', 'count': 1, 'title': 'catalog', 'status': 'Official', 'disambiguation': 'MP3', 'artist-credit': [{'name': 'WadeLen', 'artist': {'id': '6c790bba-0ca6-44ca-8334-d1cd9c860eb1', 'name': 'WadeLen', 'sort-name': 'WadeLen'}}], 'release-group': {'id': '4b0dfc27-9bfd-481c-86a7-49113e4980bb', 'type-id': 'dd2a21e1-0c00-3729-a7a0-de60b84eb5d1', 'primary-type-id': 'f529b476-6e62-324f-b0aa-1f3e33d313fc', 'title': 'catalog', 'primary-type': 'Album', 'secondary-types': ['Compilation'], 'secondary-type-ids': ['dd2a21e1-0c00-3729-a7a0-de60b84eb5d1']}, 'date': '2026-06-12', 'country': 'XW', 'release-events': [{'date': '2026-06-12', 'area': {'id': '525d4e18-3d00-31b9-a58b-a146a916de8f', 'name': '[Worldwide]', 'sort-name': '[Worldwide]', 'iso-3166-1-codes': ['XW']}}], 'track-count': 504, 'media': [{'id': '44ad4f38-ebc4-408b-b4a3-6f13807d59e3', 'position': 1, 'format': 'Digital Media', 'track': [{'id': '592c914d-35fd-442a-96ca-e41a21955684', 'number': '116', 'title': 'genre', 'length': 72000}], 'track-count': 504, 'track-offset': 115}]}, {'id': '6c70c449-125e-4269-a09a-3cd9d07c29fc', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'artist-credit-id': 'ccb88ad9-9489-4fbe-97ff-24bdb4fe9a37', 'count': 1, 'title': 'catalog', 'status': 'Official', 'disambiguation': 'AAC', 'artist-credit': [{'name': 'WadeLen', 'artist': {'id': '6c790bba-0ca6-44ca-8334-d1cd9c860eb1', 'name': 'WadeLen', 'sort-name': 'WadeLen'}}], 'release-group': {'id': '4b0dfc27-9bfd-481c-86a7-49113e4980bb', 'type-id': 'dd2a21e1-0c00-3729-a7a0-de60b84eb5d1', 'primary-type-id': 'f529b476-6e62-324f-b0aa-1f3e33d313fc', 'title': 'catalog', 'primary-type': 'Album', 'secondary-types': ['Compilation'], 'secondary-type-ids': ['dd2a21e1-0c00-3729-a7a0-de60b84eb5d1']}, 'date': '2026-06-12', 'country': 'XW', 'release-events': [{'date': '2026-06-12', 'area': {'id': '525d4e18-3d00-31b9-a58b-a146a916de8f', 'name': '[Worldwide]', 'sort-name': '[Worldwide]', 'iso-3166-1-codes': ['XW']}}], 'track-count': 504, 'media': [{'id': '89ca67fb-e066-4960-97b8-21cc7205edd5', 'position': 1, 'format': 'Digital Media', 'track': [{'id': '8a1863c1-ca81-4f38-8f26-16aa90b9f8c0', 'number': '116', 'title': 'genre', 'length': 72000}], 'track-count': 504, 'track-offset': 115}]}, {'id': 'f963ab9d-0915-48e9-a4fc-58bf1f58bd22', 'status-id': '4e304316-386d-3409-af2e-78857eec5cfe', 'artist-credit-id': 'ccb88ad9-9489-4fbe-97ff-24bdb4fe9a37', 'count': 1, 'title': 'catalog', 'status': 'Official', 'disambiguation': 'FLAC', 'artist-credit': [{'name': 'WadeLen', 'artist': {'id': '6c790bba-0ca6-44ca-8334-d1cd9c860eb1', 'name': 'WadeLen', 'sort-name': 'WadeLen'}}], 'release-group': {'id': '4b0dfc27-9bfd-481c-86a7-49113e4980bb', 'type-id': 'dd2a21e1-0c00-3729-a7a0-de60b84eb5d1', 'primary-type-id': 'f529b476-6e62-324f-b0aa-1f3e33d313fc', 'title': 'catalog', 'primary-type': 'Album', 'secondary-types': ['Compilation'], 'secondary-type-ids': ['dd2a21e1-0c00-3729-a7a0-de60b84eb5d1']}, 'date': '2026-06-15', 'country': 'XW', 'release-events': [{'date': '2026-06-15', 'area': {'id': '525d4e18-3d00-31b9-a58b-a146a916de8f', 'name': '[Worldwide]', 'sort-name': '[Worldwide]', 'iso-3166-1-codes': ['XW']}}], 'track-count': 504, 'media': [{'id': 'f86c565d-8807-42b5-9eab-43b996e0b20e', 'position': 1, 'format': 'Digital Media', 'track': [{'id': '6f19332e-1104-4985-8c7a-4650d5ba7616', 'number': '116', 'title': 'genre', 'length': 72000}

In [34]:
df = pd.json_normalize(data["recordings"])
df

,id,score,artist-credit-id,title,length,video,artist-credit,first-release-date,releases,isrcs,tags,disambiguation
0,d2fd57de-995c-41d4-be13-179d3ca7b37c,100,a4ea3a21-77ec-3f61-aed9-56e440b9f043,Pop Sub Genre,373136.0,None,"[{'name': 'Daffodill', 'artist': {'id': 'a1d48...",2024-04-25,[{'id': '4736c140-77ae-47a8-9d70-10db8d801eea'...,NaN,NaN,NaN
1,fa427675-f624-4fb4-94ff-2e0487eeeb80,91,0519cbf0-f286-3cf7-96da-8f0f13478567,Silver,NaN,None,"[{'name': 'Relese', 'artist': {'id': '34cf8d4a...",2001-03-11,[{'id': '9230145a-2f26-4f70-bc0a-18a97c0b403d'...,NaN,NaN,NaN
2,d5c6799a-8fa2-41d8-8e8e-e8e74a193ff4,82,701b6f2c-e323-4440-98a0-ea4c25e95697,Popular Music Genre,60330.0,None,"[{'name': 'Arcangel Legrand - Brotherswagg', '...",2027-12-13,[{'id': 'ce1e61ac-c76e-429f-9d41-d15f055876e2'...,NaN,NaN,NaN
3,200e5f3b-3681-4351-abeb-75c642149543,80,0f62e159-a9ad-3cac-96dd-59326497b18c,Multiple Genre Genre,NaN,None,"[{'name': 'Champion the Underdog', 'artist': {...",2014-06-06,[{'id': 'a5de97db-758d-4924-9093-a346288d393d'...,[TCABW1482324],NaN,NaN
4,31ae84bf-a0ec-413c-9c8f-824e73b9415f,79,2673e1ad-09df-30c7-b730-2e87f720d10e,Genres - Pop,107933.0,None,"[{'name': 'Brett Manning', 'artist': {'id': 'c...",NaN,[{'id': '3a21ff1f-0173-4560-83ed-23297e34ec35'...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
95,e9509129-b3f5-4334-ae4c-794a02b4ba5b,67,1bfcfdc6-4f5a-33b9-9d15-5076fadd0330,Genre Bitches,434000.0,None,"[{'name': 'Fagin’s Reject', 'artist': {'id': '...",2014-06-27,[{'id': 'a4799ed4-14c4-4740-9c1d-8af02df28ba6'...,NaN,NaN,NaN
96,5799d903-79f4-4ca9-82e6-91a8044326f2,67,6c13a5ce-eb2e-3502-8737-e38722133512,New Genre,231325.0,None,"[{'name': 'Danny Matos', 'artist': {'id': '77b...",2016-01-08,[{'id': 'df73cfaf-296c-4333-a609-26ec48c39a00'...,NaN,NaN,NaN
97,21d16f12-ded6-4323-afbb-b2df464872e1,67,1dd65c35-c379-3231-b72b-b88ec39849a9,My Genre,NaN,None,"[{'name': 'Aspects', 'artist': {'id': '602dd07...",2002,[{'id': '7f7d6136-2b44-48b7-80e9-9d3b7a4465e7'...,NaN,NaN,NaN
98,682848d9-baed-4a32-b256-ad19eced5548,67,482b9f0d-39a8-31f1-b68e-ba196b912827,Mauvais Genre,167533.0,None,"[{'name': 'Apolline', 'artist': {'id': '11aee4...",2013-01-01,[{'id': '07af4bc1-b383-4550-88dc-c0c8534be9e9'...,[FRP621566230],NaN,NaN
99,3652519d-9444-443e-8490-849f3c426264,67,b6ec8e25-3948-310c-893a-08c104b603fd,Hold Genre,252000.0,None,"[{'name': 'Paper Tiger', 'artist': {'id': 'a47...",2016-04-22,[{'id': 'f5106d8b-51bd-47b9-91b5-1eafd3ddd0e3'...,[QMLD61406153],NaN,NaN

## Check posibility for "url"  to use for spotify (to play records)
- result 100/100 is missing
- 0.09 % has isrc - too few

In [31]:
# 1. Hämta ett urval via sökning (använder mb_get från tidigare)
data = mb_get("recording", {
    "query": "firstreleasedate:[1990 TO 2000] AND tag:rock",
    "limit": 100,
})
recs = data["recordings"]

# 2. Slå upp url-relationer för varje låt
def spotify_urls(relations):
    return [
        rel["url"]["resource"]
        for rel in relations
        if "open.spotify.com" in rel.get("url", {}).get("resource", "")
    ]

rows = []
for rec in recs:
    full = mb_get(f"recording/{rec['id']}", {"inc": "url-rels isrcs"})
    urls = spotify_urls(full.get("relations", []))
    rows.append({
        "mbid": rec["id"],
        "title": rec["title"],
        "has_spotify_url": len(urls) > 0,
        "spotify_urls": urls,
        "has_isrc": len(full.get("isrcs", [])) > 0,
    })

df_check = pd.DataFrame(rows)

# 3. Hur många saknar?
print(df_check["has_spotify_url"].value_counts())
print(df_check["has_spotify_url"].mean())   # andel som har
print(df_check["has_isrc"].mean())          # andel med ISRC

has_spotify_url
False    100
Name: count, dtype: int64
0.0
0.09